### ISSUE TITLE
Illegal base64 Error

### ISSUE THREAD

**Issue by 2132aswdad** [Dumphey/item-editor#8]
Hi, i have this error using Spigot 1.20.2
- [Fri 22:04:33 ERROR Minecraft] Error occurred while enabling ItemEditor v2.0.1 (Is it up to date?)
java.lang.IllegalArgumentException: Illegal base64 character 3a
    at java.base/java.util.Base64$Decoder.decode0(Base64.java:848)
    at java.base/java.util.Base64$Decoder.decode(Base64.java:566)
    at java.base/java.util.Base64$Decoder.decode(Base64.java:589)
    at ItemEditor-2.0.1.jar//at.dumphey.itemeditor.itemeditor.storage.ItemStorage.deserializeItem(ItemStorage.java:113)
    at ItemEditor-2.0.1.jar//at.dumphey.itemeditor.itemeditor.storage.ItemStorage.loadItem(ItemStorage.java:58)
    at ItemEditor-2.0.1.jar//at.dumphey.itemeditor.itemeditor.storage.ItemStorage.reload(ItemStorage.java:37)
    at ItemEditor-2.0.1.jar//at.dumphey.itemeditor.ItemEditor.onEnable(ItemEditor.java:31)
    at

**Comment by Dumphey** [comment]
should be fixed in this new version, please check

**Comment by Chevels** [comment]
Oh thank you ! <3
What a pleasure to find Item Editor again!!! In addition there is a new interface which seems more complete than last year :)

This time the plugin load and can enable, but an base64 error persists: 

```
[14:04:39 ERROR]: [ItemEditor] Error while loading item from file /home/container/plugins/ItemEditor/items/excalibur.yml
java.lang.IllegalArgumentException: Illegal base64 character 3a
        at java.base/java.util.Base64$Decoder.decode0(Base64.java:852) ~[?:?]
        at java.base/java.util.Base64$Decoder.decode(Base64.java:570) ~[?:?]
        at java.base/java.util.Base64$Decoder.decode(Base64.java:593) ~[?:?]
        at ItemEditor 2.0.3 (1.21)-1719576279320.jar/at.dumphey.itemeditor.itemeditor.storage.ItemStorage.deserializeItem(ItemStorage.java:114) ~[ItemEditor 2.0.3 (1.21)-1719576279320.jar:?]
        at ItemEditor 2.0.3 (1.21)-1719576279320.jar/at.dumphey.itemeditor.itemeditor.storage.ItemStorage.loadItem(ItemStorage.java:59) ~[ItemEditor 2.0.3 (1.21)-1719576279320.jar:?]
        at ItemEditor 2.0.3 (1.21)-1719576279320.jar/at.dumphey.itemeditor.itemeditor.storage.ItemStorage.reload(ItemStorage.java:38) ~[ItemEditor 2.0.3 (1.21)-1719576279320.jar:?]
        at ItemEditor 2.0.3 (1.21)-1719576279320.jar/at.dumphey.itemeditor.ItemEditor.onEnable(ItemEditor.java:31) ~[ItemEditor 2.0.3 (1.21)-1719576279320.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at PlugManX-2.4.1 (1.20.6).jar/com.rylinaux.plugman.pluginmanager.PaperPluginManager.load(PaperPluginManager.java:403) ~[PlugManX-2.4.1 (1.20.6).jar:?]
        at PlugManX-2.4.1 (1.20.6).jar/com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) ~[PlugManX-2.4.1 (1.20.6).jar:?]
        at PlugManX-2.4.1 (1.20.6).jar/com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:94) ~[PlugManX-2.4.1 (1.20.6).jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:164) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:964) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at org.bukkit.craftbukkit.CraftServer.dispatchServerCommand(CraftServer.java:949) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:521) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:468) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[14:04:39 INFO]: [ItemEditor] Loaded 0 items from storage.
[14:04:39 INFO]: [ItemEditor] Enabled PlaceholderAPI support.
[14:04:39 INFO]: [PlugMan] ItemEditor has been loaded and enabled.
```

But as long as the plugin works it doesn't bother me^^
Thank you !!
